components:
  FullAdder: &fa1 fa1
  FullAdder: &fa2 fa2
wires:
  C1:
    - from: *fa1
      port: Cout
    - to: *fa2
      port: Cin
  A0:
    - from: input
    - to: *fa1
      port: A
  A1:
    - from: input
    - to: *fa2
      port: A
  B0:
    - from: input
    - to: *fa1
      port: B
  B1:
    - from: input
    - to: *fa2
      port: B
  C0:
    - from: input
    - to: *fa1
      port: Cin
  S0:
    - from: *fa1
      port: S
    - to: output
  S1:
    - from: *fa2
      port: S
    - to: output
  C2:
    - from: *fa2
      port: Cout
    - to: output
