LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY Multiplier_Smag IS
GENERIC (
	NUM_BITS_A : INTEGER := 8;
	NUM_BITS_B : INTEGER := 8
);
PORT (
	 A : IN  STD_LOGIC_VECTOR(NUM_BITS_A - 1 DOWNTO 0);
	 B : IN  STD_LOGIC_VECTOR(NUM_BITS_B - 1 DOWNTO 0);
	 O : OUT STD_LOGIC_VECTOR(NUM_BITS_A + NUM_BITS_B - 2 DOWNTO 0)
);
END Multiplier_Smag;

ARCHITECTURE carry_save OF Multiplier_Smag IS
	CONSTANT N_BITS_A         : INTEGER := NUM_BITS_A - 1;
	CONSTANT N_BITS_B         : INTEGER := NUM_BITS_B - 1;
	CONSTANT NUM_BITS_O       : INTEGER := N_BITS_A + N_BITS_B - 1;
	CONSTANT NUM_ADD_LVLS     : INTEGER := N_BITS_B - 1;
	CONSTANT NUM_AND_LVLS     : INTEGER := N_BITS_B;
	CONSTANT NUM_ADDS_PER_LVL : INTEGER := N_BITS_A;
	CONSTANT NUM_ANDS_PER_LVL : INTEGER := N_BITS_A;
BEGIN

END carry_save;
