LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY {{TOP_NAME}} IS
PORT (
	i_clk : IN STD_LOGIC;
	{{PORTS}}
);
END {{TOP_NAME}};

ARCHITECTURE arch OF {{TOP_NAME}} IS
	{{SIGNALS}}
BEGIN
----- SIGNAL ASSIGNMENTS -----
{{ASSIGNMENTS}}

----- ENTITY INSTANTIATIONS -----
{{INSTANCES}}

----- PROCESSES -----
	PROCESS (i_clk)
	BEGIN
		IF RISING_EDGE(i_clk) THEN
			{{OUTPUT_ASSIGNMENTS}}
		END IF;
	END PROCESS;
END arch;