components:
  Multiplier_2C: [2c_mag, 3, 3]
wires:
  A[0]:
    - from: input
    - to: 2c_mag
      port: A 0
  B[0]:
    - from: input
    - to: 2c_mag
      port: B 0
  A[1]:
    - from: input
    - to: 2c_mag
      port: A 1
  B[1]:
    - from: input
    - to: 2c_mag
      port: B 1
  A[2]:
    - from: input
    - to: 2c_mag
      port: A 2
  B[2]:
    - from: input
    - to: 2c_mag
      port: B 2
  O[0]:
    - from: 2c_mag
      port: O 0
    - to: output
  O[1]:
    - from: 2c_mag
      port: O 1
    - to: output
  O[2]:
    - from: 2c_mag
      port: O 2
    - to: output
  O[3]:
    - from: 2c_mag
      port: O 3
    - to: output
  O[4]:
    - from: 2c_mag
      port: O 4
    - to: output
  O[5]:
    - from: 2c_mag
      port: O 5
    - to: output
stimuli:
  - A[2]: 0
    A[1]: 1
    A[0]: 1
    B[2]: 1
    B[1]: 1
    B[0]: 1
