components:
  Multiplier: {
    name: Booth,
    A width: 8,
    B width: 8,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
wires:
  A 8:
    - from: input
    - to: Booth
      port: A 0 7
  B 8:
    - from: input
    - to: Booth
      port: B 0 7
  O 16:
    - from: Booth
      port: O 0 15
    - to: output
stimuli:
  - A: 0d-61
    B: 0d40
