components:
  Multiplier: {
    name: 2c_mag,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: carry save,
    type: inversion
  }
wires:
  A 32:
    - from: input
    - to: 2c_mag
      port: A 0 31
  B 32:
    - from: input
    - to: 2c_mag
      port: B 0 31
  O 64:
    - from: 2c_mag
      port: O 0 63
    - to: output
stimuli:
  - constraint:
#    - {wire: A, type: rng, sigma: 0.00000001, seed: 3, times: 10000}
#    - {wire: B, type: rng, sigma: 0.00000001, seed: 5, times: 10000}

# 8 bits
#    - {wire: A, type: uniform, ub: 127, lb: -128, seed: 3, times: 10000}
#    - {wire: B, type: uniform, ub: 127, lb: -128, seed: 5, times: 10000}

# 12 bits
#    - {wire: A, type: uniform, ub: 2047, lb: -2048, seed: 3, times: 10000}
#    - {wire: B, type: uniform, ub: 2047, lb: -2048, seed: 5, times: 10000}

# 16 bits
#    - {wire: A, type: uniform, ub: 32767, lb: -32768, seed: 3, times: 10000}
#    - {wire: B, type: uniform, ub: 32767, lb: -32768, seed: 5, times: 10000}

# 24 bits
    - {wire: A, type: uniform, ub: 8388607, lb: -8388608, seed: 3, times: 10000}
    - {wire: B, type: uniform, ub: 8388607, lb: -8388608, seed: 5, times: 10000}

# 30 bits
#    - {wire: A, type: uniform, ub: 536870911, lb: -536870912, seed: 3, times: 10000}
#    - {wire: B, type: uniform, ub: 536870911, lb: -536870912, seed: 5, times: 10000}
