components:
  Multiplier: {
    name: Booth,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
wires:
  A 32:
    - from: input
    - to: Booth
      port: A 0 31
  B 32:
    - from: input
    - to: Booth
      port: B 0 31
  O 64:
    - from: Booth
      port: O 0 63
    - to: output
stimuli:
  - constraint:
    - {wire: A, type: rng, sigma: 0.00000001, seed: 3, times: 10000}
    - {wire: B, type: rng, sigma: 0.00000001, seed: 5, times: 10000}
