components:
  Multiplier_2C: [2c_mag, 32, 32]
wires:
  A 32:
    - from: input
    - to: 2c_mag
      port: A 0 31
  B 32:
    - from: input
    - to: 2c_mag
      port: B 0 31
  O 64:
    - from: 2c_mag
      port: O 0 63
    - to: output
stimuli:
  - A: 0x40000005
    B: 0x7
  - A: 0x4000000A
  - A: 0x40000002
  - A: 0x40000006
#  - A: 0x80000005
#    B: 0x80000007
#  - A: 0x5
#    B: 0x7
#  - A: 0x80000005
#    B: 0x80000007
