components:
  Multiplier_Smag: [smag, 32, 32]
wires:
  A 32:
    - from: input
    - to: smag
      port: A 0 31
  B 32:
    - from: input
    - to: smag
      port: B 0 31
  O 63:
    - from: smag
      port: O 0 63
    - to: output
stimuli:
  - constraint: {wire: A, begin_index: 0, end_index: 5, type: rng, seed: 4}
    A: 0x40000005
    B: 0x7
  - A: 0x4000000A
  - A: 0x40000002
  - A: 0x40000006
#  - A: 0x80000005
#    B: 0x80000007
#  - A: 0x5
#    B: 0x7
#  - A: 0x80000005
#    B: 0x80000007
