components:
  Multiplier: {
    name: real_mul,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  Multiplier: {
    name: imag_mul,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  RippleCarryAdder: [real_add, 32]
  RippleCarrySubtracter: [real_sub, 32]
  RippleCarryAdder: [imag_add, 32]
  RippleCarrySubtracter: [imag_sub, 32]
wires:
  real_x0 32:
    - from: input
    - to: [real_add, real_sub]
      port: [A 0 31, A 0 31]
  real_x1 32:
    - from: input
    - to: real_mul
      port: A 0 31
  real_twiddle 32:
    - from: input
    - to: real_mul
      port: B 0 31
  real_O 32:
    - from: real_mul
      port: O 0 31
    - to: [real_add, real_sub]
      port: [B 0 31, B 0 31]
  real_F0 32:
    - from: real_add
      port: O 0 31
    - to: output
  real_F1 32:
    - from: real_sub
      port: O 0 31
    - to: output
  imag_x0 32:
    - from: input
    - to: [imag_add, imag_sub]
      port: [A 0 31, A 0 31]
  imag_x1 32:
    - from: input
    - to: imag_mul
      port: A 0 31
  imag_twiddle 32:
    - from: input
    - to: imag_mul
      port: B 0 31
  imag_O 32:
    - from: imag_mul
      port: O 0 31
    - to: [imag_add, imag_sub]
      port: [B 0 31, B 0 31]
  imag_F0 32:
    - from: imag_add
      port: O 0 31
    - to: output
  imag_F1 32:
    - from: imag_sub
      port: O 0 31
    - to: output
stimuli:
  - real_x0: 0d-8000
    real_x1: 0d8000
    real_twiddle: 0d1
    imag_x0: 0d0
    imag_x1: 0d0
    imag_twiddle: 0d1
