components:
  Multiplier: {
    name: real_mul_0,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  Multiplier: {
    name: imag_mul_0,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  Multiplier: {
    name: real_mul_1,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  Multiplier: {
    name: imag_mul_1,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
  RippleCarryAdder: [mul_add, 32]
  RippleCarrySubtracter: [mul_sub, 32]
  RippleCarryAdder: [complex_add_0, 32]
  RippleCarryAdder: [complex_add_1, 32]
  RippleCarrySubtracter: [complex_sub_0, 32]
  RippleCarrySubtracter: [complex_sub_1, 32]
wires:
  real_x0 32:
    - from: input
    - to: [complex_add_0, complex_sub_0]
      port: [A 0 31, A 0 31]
  imag_x0 32:
    - from: input
    - to: [complex_add_1, complex_sub_1]
      port: [A 0 31, A 0 31]
  real_x1 32:
    - from: input
    - to: [real_mul_0, imag_mul_1]
      port: [A 0 31, A 0 31]
  imag_x1 32:
    - from: input
    - to: [real_mul_1, imag_mul_0]
      port: [A 0 31, A 0 31]
  real_twiddle 32:
    - from: input
    - to: [real_mul_0, imag_mul_0]
      port: [B 0 31, B 0 31]
  imag_twiddle 32:
    - from: input
    - to: [real_mul_1, imag_mul_1]
      port: [B 0 31, B 0 31]
  real_mul_O_0 32:
    - from: real_mul_0
      port: O 0 31
    - to: mul_sub
      port: A 0 31
  real_mul_O_1 32:
    - from: real_mul_1
      port: O 0 31
    - to: mul_sub
      port: B 0 31
  imag_mul_O_0 32:
    - from: imag_mul_0
      port: O 0 31
    - to: mul_add
      port: A 0 31
  imag_mul_O_1 32:
    - from: imag_mul_1
      port: O 0 31
    - to: mul_add
      port: B 0 31
  real_O 32:
    - from: mul_sub
      port: O 0 31
    - to: [complex_add_0, complex_sub_0]
      port: [B 0 31, B 0 31]
  imag_O 32:
    - from: mul_add
      port: O 0 31
    - to: [complex_add_1, complex_sub_1]
      port: [B 0 31, B 0 31]
  real_F0 32:
    - from: complex_add_0
      port: O 0 31
    - to: output
  imag_F0 32:
    - from: complex_add_1
      port: O 0 31
    - to: output
  real_F1 32:
    - from: complex_sub_0
      port: O 0 31
    - to: output
  imag_F1 32:
    - from: complex_sub_1
      port: O 0 31
    - to: output
stimuli:
  - real_x0: 0d-8000
    imag_x0: 0d0
    real_x1: 0d8000
    imag_x1: 0d0
    real_twiddle: 0d1
    imag_twiddle: 0d1
