components:
  Multiplier: {
    name: realmul,
    A width: 32,
    B width: 32,
    number format: 2C,
    layout: booth radix-4,
    type: none
  }
#  Multiplier: {
#    name: imagmul,
#    A width: 32,
#    B width: 32,
#    number format: 2C,
#    layout: booth radix-4,
#    type: none
#  }
  RippleCarryAdder: [rca, 32]
  RippleCarrySubtracter: [rcs, 32]
wires:
  realx0 32:
    - from: input
    - to: [rca, rcs]
      port: [A 0 31, A 0 31]
  realx1 32:
    - from: input
    - to: realmul
      port: A 0 31
  realtwiddle 32:
    - from: input
    - to: realmul
      port: B 0 31
  realO 32:
    - from: realmul
      port: O 0 31
    - to: [rca, rcs]
      port: [B 0 31, B 0 31]
  realF0 32:
    - from: rca
      port: O 0 31
    - to: output
  realF1 32:
    - from: rcs
      port: O 0 31
    - to: output
#  imagx0 32:
#    - from: input
#    - to: [rca, rcs]
#      port: [A 0 31, A 0 31]
#  imagx1 32:
#    - from: input
#    - to: imagmul
#      port: A 0 31
#  imagtwiddle 32:
#    - from: input
#    - to: imagmul
#      port: B 0 31
#  imagO 32:
#    - from: imagmul
#      port: O 0 31
#    - to: [rca, rcs]
#      port: [B 0 31, B 0 31]
#  imagF0 32:
#    - from: rca
#      port: O 0 31
#    - to: output
#  imagF1 32:
#    - from: rcs
#      port: O 0 31
#    - to: output
stimuli:
  - realx0: 0d-8000
    realx1: 0d8000
    realtwiddle: 0d1
#    imagx0: 0d0
#    imagx1: 0d0
#    imagtwiddle: 0d1
