components:
  FullAdder: &fa1 fa1
  FullAdder: &fa2 fa2
wires:
  C1:
    - from: *fa1
      port: Cout
    - to: *fa2
      port: Cin
  &InData InData:
    - from: input
    - to: [*fa1, *fa1, *fa2, *fa2]
      port: [A, B, A, B]
  &C0 C0:
    - from: input
    - to: *fa1
      port: Cin
  S0:
    - from: *fa1
      port: O

      #oirt: O
      #port: 
      #port: [O]
      #port: {O}
    - to: output
  S1:
    - from: *fa2
      port: O
    - to: output

    #- to: {}
    #- to: []
    #- 
    #- to:
    #- to2:
    #- to
    #- [to]
  &C2 C2:
    - from: *fa2
    #- from: fa3
      port: Cout
      #port: [Cout]
    - to: output
stimuli:
  - *InData : true
    *C0 : true
  - *InData : false
    *C0 : true
