components:
  Xor: &xor xor
  And: &and and
  HalfAdder: &ha ha
wires:
  &A A:
    - from: input
    - to: [*xor, *and, *ha]
      port: [A, A, A]
  &B B:
    - from: input
    - to: [*xor, *and, *ha]
      port: [B, B, B]
  Sxor:
    - from: *xor
      port: O
    - to: output
  Cand:
    - from: *and
      port: O
    - to: output
  Sha:
    - from: *ha
      port: O
    - to: output
  Cha:
    - from: *ha
      port: C
    - to: output
stimuli:
  - *A : 1
    *B : 1
