components:
  FullAdder: fa
  And: and
  Not: not
wires:
  A:
    - from: input
    - to: fa
      port: A
  B:
    - from: input
    - to: fa
      port: B
  Ci:
    - from: input
    - to: fa
      port: Cin
  Co:
    - from: fa
      port: Cout
    - to: output
  AndA:
    - from: fa
      port: S
    - to: and
      port: A
  AndB:
    - from: fa
      port: Cout
    - to: and
      port: B
  AndO:
    - from: and
      port: O
    - to: not
      port: I
  Not:
    - from: not
      port: O
    - to: output
stimuli:
  - A: 1
    B: 1
    Ci: 1
  - A: 0
    B: 0
