components:
  Multiplier_Smag: [smag, 3, 3]
wires:
  A 3 smag:
    - from: input
    - to: smag
      port: A 0 2
  B 3 smag:
    - from: input
    - to: smag
      port: B 0 2
  O 5:
    - from: smag
      port: O 0 4
    - to: output
stimuli:
  - A: 0b110
    B: 0b111
