components:
  Multiplier_Smag: [smag, 4, 4]
wires:
  A 4 smag:
    - from: input
    - to: smag
      port: A 0 3
  B 4 smag:
    - from: input
    - to: smag
      port: B 0 3
  O 7 smag:
    - from: smag
      port: O 0 6
    - to: output
stimuli:
  - A: 0b1011
    B: 0b0111
